package LeetCode;

import java.util.HashMap;

/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e
Explanation:
'e' is the letter that was added.

 */

public class n389_Find_the_Difference {
	//HashMap 
	public char findTheDifference(String s, String t) {
		HashMap<Character, Integer> map = new HashMap<Character, Integer>();
		
		for(int i=0; i<s.length(); i++) {
            map.put(s.charAt(i), map.getOrDefault(s.charAt(i), 0)+1);	//getOrDefault()
        }
		
        for(int i=0; i<t.length(); i++) {
            map.put(t.charAt(i), map.getOrDefault(t.charAt(i), 0)-1);
            
            if(map.get(t.charAt(i)) < 0) {
                return t.charAt(i);
            }
        }
        
		return 0;
	}
	//+-
	public char findTheDifference2(String s, String t) {
		char res = 0;
		
		for(int i=0; i<s.length(); i++) { 
			res -= s.charAt(i);						//can't use res = res - s.charAT(i)
		}
		
		for(int i=0; i<t.length(); i++) { 
			res += t.charAt(i);
		}
		
		return res;
	}
	public static void main(String[] args) {
		n389_Find_the_Difference obj = new n389_Find_the_Difference();
		String s = "abcde";
		String t = "abcdee";
		System.out.println(obj.findTheDifference(s, t));
		System.out.println(obj.findTheDifference2(s, t));
	}
}
